server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis-plus-first?serverTimezone=GMT%2b8
    username: root
    password: qwer1234

mybatis-plus:
  global-config:
    db-config:
      id-type: auto # id??????????????????????
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql????
  mapper-locations: classpath:mapper/*.xml  #????????sqlmapper????
  type-aliases-package: roydon.xyz.mybatisplusdemo.entity